<a href="https://colab.research.google.com/github/abhishekDey11209/ML-projects/blob/main/Multiple_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("50_Startups.csv")

In [ ]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [ ]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
lc = LinearRegression()
lc.fit( X_train, y_train)

LinearRegression()

In [ ]:
y_predict = lc.predict(X_test)
np.printoptions(precision =2)

In [ ]:
y_test.reshape(-1, 1)

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [ ]:
y_predict.reshape(-1, 1)

array([[103015.20159795],
       [132582.27760816],
       [132447.73845175],
       [ 71976.09851258],
       [178537.48221057],
       [116161.24230167],
       [ 67851.69209676],
       [ 98791.73374687],
       [113969.43533014],
       [167921.06569552]])

In [ ]:
result = np.hstack((y_test.reshape(-1, 1), y_predict.reshape(-1, 1)))

In [ ]:
result

array([[103282.38      , 103015.20159795],
       [144259.4       , 132582.27760816],
       [146121.95      , 132447.73845175],
       [ 77798.83      ,  71976.09851258],
       [191050.39      , 178537.48221057],
       [105008.31      , 116161.24230167],
       [ 81229.06      ,  67851.69209676],
       [ 97483.56      ,  98791.73374687],
       [110352.25      , 113969.43533014],
       [166187.94      , 167921.06569552]])